ENT.Base 		= "npc_vj_human_base"
ENT.Type 		= "ai"
ENT.PrintName 		= "grunt"
ENT.Author 		= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Category		= "madness combat remake"
